default: &default
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  host: <%= ENV.fetch('POSTGRESQL_ADDRESS', 'localhost') %>
  port: <%= ENV.fetch('POSTGRESQL_PORT', 5432) %>
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', 'admin') %>
  database: <%= ENV.fetch('POSTGRESQL_DATABASE', 'perf-monitor_development') %>

development:
  <<: *default

test:
  <<: *default
  database: perf-monitor_test

production:
  <<: *default

